### ISSUE TITLE
Get JSON list of images from a new source

### ISSUE THREAD

**Issue by andreweick** [andreweick/eick.com#156]
I found that maintaining my own database was more work than I wanted!  So I'm migrating my images from that homegrown AWS database to Cloudflare Images.

Notwithstanding [Build pages from data source](https://github.com/gohugoio/hugo/issues/5074) which would make it so nice to use!

** Deleting old API ** -- adding *new* api in https://github.com/andreweick/eick.com/issues/156#issuecomment-997463582

**Comment by andreweick** [comment]
ok, 4000 images in, I think my keys are wrong

**Comment by regisphilibert** [comment]
Hi @andreweick I started getting into this and I have a few comments:

## Data
### The new API lacks information for each image. We miss:
- Classifications
- Artist

## Filenames and URLs
With S3, the parameter used to fetch the image data (for on-demand builders) is the filename (`20190127-voice-recital-0095.jpg`) so it was safe use that in our URL, as we could safely use `/photo/20190127-voice-recital-0095.jpg` and the use the last part to fetch the image data from the API. 
But with cloudflare it is the image ID. (`000b6b49-c71e-412c-5222-a20e37883b00`) so our URL will not look as pretty: `/photo/000b6b49-c71e-412c-5222-a20e37883b00`.

Of course this would be leveraged by what we do on the following remark (no demand builders, then no need for ugly urls)

## 1000 built images vs all ~ 9000

As you know we used to to only fetch 1000 images with the netlify build plugin so Hugo only built 1000, the rest was handled by an on-demand builder. We did this because the former API limited us to one endpoint per page. Which means for 1000 images, we needed to ping the API 1000 times which was a lot and above that, it could break the build.

Now with Cloudflare we have an endpoint (paginated max at 100 per page) which returns the list of images.
This means with only 90 ping to the API we can retrieve the data for all 8882 images.

### What does it mean for us?

I think it's safe to grab all the images and stop relying on on-demand builders for the majority of them. But it does take a longer time to build
1 - Retrieving all ~ 9000 images. Hugo builds them all: 
- pre-build plugin takes **22s**
- Hugo (on my machine) takes **23s**
- Total: 1 minute. This will be doubled at least on Netlify.
- Netlify pushing 9000 files to CDN: Never too sure but several minutes. This only need to happen on some builds (all pages updated)

2 - Retrieving all ~9000 images but Hugo only builds 1000 (rest is on-demand builders):
- pre-build plugin takes **22s**
- Hugo (on my machine) takes **6s**
- Total: 10s. This will be doubled at least on Netlify.
- Netlify pushing ~ 1000 files to CDN: Not sure but less than 10000 I would think.

Now solution 2 is fastest, but relies on on-demand builders. It would really be interesting if we did not have to fetch the full data of 9000 image, to make it really interesting. But I don't think there is an endpoint that just that, namely:
Get me an array of ids or filenames of ALL images and nothing more.

**Comment by andreweick** [comment]
I don't know how how to edit in line:

## Losing the classification / artists.
Yeah, that's a drag, I want to build it back in (future sprint?) but the current API didn't support it.

## new endpoints
Given a weekend, I think I could write two new end points -- 
1. Given a Filename (or a UID) returns a UID (or a filename)
2. Returns all 9K image in an JSON array.  Since the images change very rarely I would just build the array on Upload and then store it somewhere (like s3 or such).  The (new) endpoint would just be UID's (as you can see, the URL variations just vary the end).  The endpoint wouldn't have the notion of Paging or Pagesize, and also wouldn't need any authentication

Would that work better than the current endpoint?

**Comment by regisphilibert** [comment]
### Endpoints

I think we only need one endpoint to list all images:

```json
[
  {
    "id": "cf4a1daf-b5cf-4149-23dd-c3d8be04d500",
    "filename": "zion_np2.jpg"
  },
  {
    "id": "6ce0bf30-3249-4366-707b-97daa1864700",
    "filename": "zion_np.jpg"
  },
  {
    "id": "8dfc3269-8283-497a-7969-0d9a39313e00",
    "filename": "yucca_bloom.jpg"
  },
  {
    "id": "f5fb3708-497f-44f8-d888-dbb38297d100",
    "filename": "young_crown_prince_bertil.jpg"
  },
  {
    "id": "99cbe15e-8786-496f-3e1e-2ece55f75f00",
    "filename": "yosemite_scenery_ng.jpg"
  }
  {...}
]
```

1. build plugin could use to populate the term holder page at minimum
2. Hugo could use it to generate the URL rewrites:
   From: /photo/yosemite_scenery_ng.jpg
   To: /.netlify/function/photo/99cbe15e-8786-496f-3e1e-2ece55f75f00
3. Hugo could use it to find images from their slug/ID.

**Comment by andreweick** [comment]
Makes sense, I'll create an endpoint that returns a JSON of all the photos similar to ☝️.  If I add a date field to the array, then can hugo sort at build time?  That gives a bit of flexibility...

You have the URL re-write to a netlify function -- with the migration away from netlify that would be a Plain Old javascript function (or are you thinking something else?)

**Comment by andreweick** [comment]
New Endpoints:

```bash
curl http://edc-router.missionfocus.workers.dev/edcList/minimal | jq
```

```json
[
  {
    "date": "2021-11-13T11:00:33.526Z",
    "id": "cf4a1daf-b5cf-4149-23dd-c3d8be04d500",
    "filename": "zion_np2.jpg",
    "requireSignedURLs": false
  },
  {
    "date": "2021-11-13T11:00:27.196Z",
    "id": "6ce0bf30-3249-4366-707b-97daa1864700",
    "filename": "zion_np.jpg",
    "requireSignedURLs": false
  },
  {
    "date": "2021-11-13T11:00:20.606Z",
    "id": "8dfc3269-8283-497a-7969-0d9a39313e00",
    "filename": "yucca_bloom.jpg",
    "requireSignedURLs": false
  },
  {
    "date": "2021-11-13T11:00:14.529Z",
    "id": "f5fb3708-497f-44f8-d888-dbb38297d100",
    "filename": "young_crown_prince_bertil.jpg",
    "requireSignedURLs": false
  },
  {
    "date": "2021-11-13T11:00:08.668Z",
    "id": "99cbe15e-8786-496f-3e1e-2ece55f75f00",
    "filename": "yosemite_scenery_ng.jpg",
    "requireSignedURLs": false
  },
  {
    "date": "2021-11-13T11:00:02.660Z",
    "id": "c8dc52de-7a19-400e-4841-3b88f17a4d00",
    "filename": "yosemite_scenery.jpg",
    "requireSignedURLs": false
  },
  {
    "date": "2021-11-13T10:59:56.525Z",
    "id": "be893d12-79f0-41b1-96c5-e465958f6800",
    "filename": "yosemite_scenery-2.jpg",
    "requireSignedURLs": false
  },
  {
    "date": "2021-11-13T10:59:50.328Z",
    "id": "1b1459c8-1b9f-4c0d-bef2-df734a643400",
    "filename": "yosemite_falls_dry_now.jpg",
    "requireSignedURLs": false
  }
]
```


Just for fun, I added a "full" option also, so you can double checck the URL;s

```bash
curl http://edc-router.missionfocus.workers.dev/edcList/full | jq | head -50
```

```json
[
  {
    "id": "cf4a1daf-b5cf-4149-23dd-c3d8be04d500",
    "filename": "zion_np2.jpg",
    "uploaded": "2021-11-13T11:00:33.526Z",
    "requireSignedURLs": false,
    "variants": [
      "https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/cf4a1daf-b5cf-4149-23dd-c3d8be04d500/w320",
      "https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/cf4a1daf-b5cf-4149-23dd-c3d8be04d500/w960signed",
      "https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/cf4a1daf-b5cf-4149-23dd-c3d8be04d500/square200",
      "https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/cf4a1daf-b5cf-4149-23dd-c3d8be04d500/public",
      "https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/cf4a1daf-b5cf-4149-23dd-c3d8be04d500/w1920",
      "https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/cf4a1daf-b5cf-4149-23dd-c3d8be04d500/w960",
      "https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/cf4a1daf-b5cf-4149-23dd-c3d8be04d500/square150",
      "https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/cf4a1daf-b5cf-4149-23dd-c3d8be04d500/w1280",
      "https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/cf4a1daf-b5cf-4149-23dd-c3d8be04d500/w2560",
      "https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/cf4a1daf-b5cf-4149-23dd-c3d8be04d500/w640",
      "https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/cf4a1daf-b5cf-4149-23dd-c3d8be04d500/square100"
    ]
  },
  {
    "id": "6ce0bf30-3249-4366-707b-97daa1864700",
    "filename": "zion_np.jpg",
    "uploaded": "2021-11-13T11:00:27.196Z",
    "requireSignedURLs": false,
    "variants": [
      "https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/6ce0bf30-3249-4366-707b-97daa1864700/w320",
      "https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/6ce0bf30-3249-4366-707b-97daa1864700/w960signed",
      "https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/6ce0bf30-3249-4366-707b-97daa1864700/square200",
      "https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/6ce0bf30-3249-4366-707b-97daa1864700/public",
      "https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/6ce0bf30-3249-4366-707b-97daa1864700/w1920",
      "https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/6ce0bf30-3249-4366-707b-97daa1864700/w960",
      "https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/6ce0bf30-3249-4366-707b-97daa1864700/square150",
      "https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/6ce0bf30-3249-4366-707b-97daa1864700/w1280",
      "https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/6ce0bf30-3249-4366-707b-97daa1864700/w2560",
      "https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/6ce0bf30-3249-4366-707b-97daa1864700/w640",
      "https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/6ce0bf30-3249-4366-707b-97daa1864700/square100"
    ]
  },
  {
    "id": "8dfc3269-8283-497a-7969-0d9a39313e00",
    "filename": "yucca_bloom.jpg",
    "uploaded": "2021-11-13T11:00:20.606Z",
    "requireSignedURLs": false,
    "variants": [
      "https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/8dfc3269-8283-497a-7969-0d9a39313e00/w320",
      "https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/8dfc3269-8283-497a-7969-0d9a39313e00/w960signed",
      "https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/8dfc3269-8283-497a-7969-0d9a39313e00/square200",
      "https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/8dfc3269-8283-497a-7969-0d9a39313e00/public",
      "https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/8dfc3269-8283-497a-7969-0d9a39313e00/w1920",
❯ edc-router (master) ✘

```

**Comment by regisphilibert** [comment]
Hi @andreweick this weekend I experimented with yet another workaround to building pages from a remote source from Hugo...

It recently came to me that we did not need a neltify build plugin to run that « fetch API and build files » first step.

Hugo is perfectly capable of doing that work by itself. So instead of a having Netlify run our plugin and then run Hugo,
we’ll just run Hugo twice.

The first pass will build a minimal Hugo project which will call the API and generate markdown files from its response (thanks to Hugo asset pipeline [resources.FromString](https://gohugo.io/hugo-pipes/resource-from-string/#readout method).

The second pass just builds the usual site (only it will mount the markdown files outputted by the first pass onto its own content directory).

```yaml
module:
  mounts:
  - source: remote/public/photo
     target: content/photo
```

Voilà. I’ve already tested the approach and it works (and is blazing fast). Now I just need to see it run on a production site for weeks on end.

The advantages are:

- We have real Hugo Pages, so we can do taxonomy etc…
- We don't need on-demand builders anymore, Hugo will build everything without a sweat.
- No more CI dependency, this will work anywhere regardless of your CI capabilities.
- It works locally without Netlify Dev etc…
- We only use Hugo, so no more NodeJS dependency either. (Netlify is limiting its build plugin to NodeJS)
- We can use Hugo’s own caching API to avoid fetching the API endpoints on every build.

```yaml
caches:
  getresource:
    maxAge: 1day
```
As for « do we need to build the files on every build? », I still have to investigate, but I don’t think so as Netlify will likely keep the files intact unless its runs a « clear cache and deploy »  build. But nevertheless, it takes 1 second to write those 9000 files, so we might as well write them every time 🤷‍♂️

I’ll try this approach on your site this week if you don’t have any reservations.

This does mean the new (all images) endpoint was not necessary after all, I do hope you did not spend too much time on it… Though I could use it to fetch the number of image and calculate the number of pages I need to go through. Might save us 1 millisecond :)

**Comment by regisphilibert** [comment]
@andreweick this is good and working on https://github.com/andreweick/eick.com/pull/173

The new api endpoint works great, but it's not protected. I think I understood that it bears the signed urls, so maybe you should protect it? Not sure, might be missing something.

**Comment by andreweick** [comment]
@regisphilibert Yes Sir -- you are right, I was going to leave them open while you are developing (I'll monitor bandwidth just in case some bot gets it) -- Once you have finished development, I'll lock the endpoints down to only work if originating from an eick.com address....

**Comment by regisphilibert** [comment]
Ok.

**Comment by andreweick** [comment]
Can't wait to see how this turns out @regisphilibert -- I'd love to get rid of the NPM build and depend only on the hugo build...

**Comment by regisphilibert** [comment]
It's already in place on the PR
