### ISSUE TITLE
photo sets broken into "groups"

### ISSUE THREAD

**Issue by andreweick** [andreweick/eick.com#95]
Make an API that returns all the images for the passed-in day (YYYY-MM-DD).  Have 1 page per day.  Also have the 1 page per Tag.

Change the API to group photos by
1. Year
2. Month
3. Day
4. Tag?

**Comment by regisphilibert** [comment]
I think we can once again use on-demand builders for this task if we stay out of pagination. So basically it would just be a page at `/photo/yyyy-mm-dd` that returns the full list of pictures returned by the API when inputing the given date.

For me only a list of filename would suffice as this is what we're used to (fetching image data from filename) but if it's the same to you and you can improve the API to return a list of objects with basic image data (filename, artist, etc...) then the function could just fetch one endpoint instead of having to fetch the 
1. date endpoint which returns the filename list
2. every endpoint of returned images

**Comment by andreweick** [comment]
@regisphilibert yes, I think I can do that — I can extend the API to return a full JSON object for each photo.  That way you can loop through w/o needing another API call.  There is 1 MB payload limit, but I can’t imagine being close to that (if broken by day)

I’ll get something in a day or two

#GoHabs

**Comment by andreweick** [comment]
@regisphilibert you’d still need 2 API calls though, no?  1st to enumerate “all possible YYY-MM-DD’s” and 2nd to return “photo object” for given YYYY-MM-DD, right? — the outer and inner loop of the builder?

**Comment by regisphilibert** [comment]
mmm I guess so...

1. Get all existing days... which I cannot do without fetching the data of all 6000 images. So I guess you could provide an endpoint which list "existing dates". This endpoint I will use during the "pre-build" step that Hugo is aware of the existence of those "pages". 
2. Get data object of all images from a group (group can be a date, a month, a year or a tag) This will be used by the on-demand builder when a user lands on a "group" page.

Maybe before coding we could define how the user will access the link for any given group...

**Comment by andreweick** [comment]
@regisphilibert I think we should kick this to sprint +1 -- I need to do some back end work as well as get the usage patterns down before you can start coding...
